name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  first_job:
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo "hello!"

  notify_slack:
    runs-on: ubuntu-latest
    needs: [ first_job ]
    if: always() && ${{ github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "Playground {workflow} has {status_message}"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required