name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '*/5 * * * *'
env:
  MODULE_NAME: 'Playground'

jobs:
  first_job:
    strategy:
      matrix:
        php:
          - '8.0'
          - '8.1'
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo "hello!"

  notify_slack:
    runs-on: ubuntu-latest
    needs: [ first_job ]
    if: always() && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    steps:
      - uses: ravsamhq/notify-slack-action@v2
        if: job.status == 'success'
        with:
          status: 'success'
          message_format: "{emoji} *${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Scheduled' }} ${{ env.MODULE_NAME }} {workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - uses: ravsamhq/notify-slack-action@v2
        if: job.status == 'failure' || job.status == 'success'
        with:
          status: 'failure'
          message_format: "{emoji} *${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Scheduled' }} ${{ env.MODULE_NAME }} {workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}