name: Development

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '*/5 * * * *'
env:
  MODULE_NAME: 'Playground'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Do something
        run: |
          echo "hello!"

  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Do fail
        run: exit 1

  notify_slack:
    runs-on: ubuntu-latest
    needs: [ first_job ]
    if: always() && (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule')
    steps:
      - uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status == 'failure' && 'failure' || 'success' }}
          notification_title: >
            *${{ github.event_name == 'workflow_dispatch' && 'Manual' || 'Scheduled' }} ${{ env.MODULE_NAME }} {workflow}*
          message_format: >
            {emoji} {status_message} in <{repo_url}|{repo}>
          footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}